packages:
  - 'apps/*'
  - 'packages/*'
  - 'database'
  - 'tests'

onlyBuiltDependencies:
  - '@embedded-postgres/windows-x64'
  - '@swc/core'
  - '@prisma/client'
  - '@prisma/engines'
  - 'esbuild'
  - 'prisma'
  - 'unrs-resolver'
  - 'sharp'
