export type View =
  | 'dashboard'
  | 'my-learning'
  | 'learning-path'
  | 'assessments'
  | 'assignments'
  | 'calendar'
  | 'discussions'
  | 'certificates'
  | 'ai-tutor'
  | 'progress'
  | 'notifications'
  | 'course-player'
  | 'quiz'
