export { prisma, checkDatabaseConnection } from './client';
export {
  PrismaClient,
  Prisma,
  RoleKey,
  UserStatus,
  DepartmentStatus,
  CourseStatus,
  CourseDifficulty,
  CourseVisibility,
  ContentType,
  ContentItemStatus,
  EnrollmentStatus,
  EnrollmentSource,
  ContentProgressStatus,
  LearningPathStatus,
  AssignmentTargetType,
  AssignmentScopeType,
  CertificateStatus,
  NotificationType,
} from '@prisma/client';
export type {
  Organization,
  OrganizationStatus,
  Role,
  Permission,
  RolePermission,
  Membership,
  User,
  Department,
  Course,
  Category,
  Module,
  ContentItem,
  Enrollment,
  ContentProgress,
  LearningPath,
  LearningPathCourse,
  LearningPathEnrollment,
  Assignment,
  Assessment,
  Question,
  AssessmentAttempt,
  Certificate,
  Notification,
  NotificationPreference,
} from '@prisma/client';
